version: '3'
services:
  devon:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
    stdin_open: true
    tty: true